- name: Ensure required variables are defined
  ansible.builtin.assert:
    that:
      - base_dir is defined
      - admin_user is defined
      - admin_pass is defined
    fail_msg: >
      Required variables not set. Ensure you define 'base_dir', 'admin_user', and 'admin_pass'.

- name: Gather facts from the node
  ansible.builtin.setup:
  run_once: true

- name: Create grafana directories
  file:
    path: "{{ base_dir }}/{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - ''
    - 'data'
    - 'provisioning'
    - 'provisioning/datasources'

- name: Render docker-compose.yml.j2
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ base_dir }}/docker-compose.yml"
    mode: "0600"

- name: Start grafana
  ansible.builtin.shell: docker compose up -d
  args:
    chdir: "{{ base_dir }}"
