services:
  cloudflare-ddns:
    image: favonia/cloudflare-ddns:edge-alpine
    network_mode: host
    restart: unless-stopped
    user: "1000:1000"
    read_only: true
    cap_drop: [all]
    security_opt: [no-new-privileges:true]
    env_file:
      - .env
